### PR TITLE
Lauknload patch 1

### PR DESCRIPTION
**Pull request by lauknload**
I'm learning github man feel free to give tips

### CODE REVIEW

**Comment by JamsheedMistri** [comment]
@lauknload it says this PR is still a work in progress. Are you done? If so, please mark it as ready for review.

**Comment by lauknload** [comment]
> @lauknload it says this PR is still a work in progress. Are you done? If so, please mark it as ready for review.

Not finished with this patch yet. I got a bit of a headache figuring this github all out for the first time, and left it alone for a month. I'll get back to it and then I'll mark it as ready for review

**Comment by lauknload** [comment]
For some reason I tried adding four new swords to this patch and it created a different pull request or something. Hope you are able to see it

**Comment by JamsheedMistri** [comment]
It says you haven't made any changes since 4 months ago when you said it's not yet ready. Are you sure this is ready for review?

**Comment by JamsheedMistri** [comment]
Never mind, I see what you did. Approving now!

**Review by JamsheedMistri — APPROVED** [review]

**Pull request closed without merging**
